data:
  image: jakubigla/docker-data-only
  volumes:
   - /docker-data/jenkins_home:/var/jenkins_home
  entrypoint: ["true"]
  restart: always
jenkins:
  image: jenkins
  ports:
   - "8000:8080"
  volumes:
   - /var/jenkins_home
  tty: true
  restart: always
production:
  image: jakubigla/docker-apache-php
  ports:
   - "127.0.0.1:8080:8080"
  volumes_from:
     - "data"
  tty: true
  restart: always