jenkinsdata:
  image: jakubigla/jenkins-data-only
  volumes:
   - /docker-data/jenkins_home:/var/lib/jenkins
   - /git:/git
productiondata:
  image: jakubigla/web-data-only
  volumes:
   - /docker-data/production/www:/www
   - /docker-data/production/vhosts:/etc/apache2/sites-enabled
   - /docker-data/production/log:/var/log

stagingdata:
  image: jakubigla/web-data-only
  volumes:
   - /docker-data/staging/www:/www
   - /docker-data/staging/vhosts:/etc/apache2/sites-enabled
   - /docker-data/staging/log:/var/log

productionmysqldata:
 image: jakubigla/mysql-data-only
 volumes:
  - /docker-data/production/mysql/data:/var/lib/mysql

stagingmysqldata:
 image: jakubigla/mysql-data-only
 volumes:
  - /docker-data/staging/mysql/data:/var/lib/mysql

jenkins:
  image: jakubigla/jenkins-php
  ports:
   - "8000:8080"
  volumes:
   - /docker-data/production/www:/www/production
   - /docker-data/staging/www:/www/staging
  volumes_from:
   - "jenkinsdata"
  tty: true
  restart: always

productionmysql:
  image: mysql
  volumes_from:
   - "productionmysqldata"
  environment:
    MYSQL_ROOT_PASSWORD: password
  tty: true
  restart: always

stagingmysql:
  image: mysql
  ports:
     - "3307:3306"
  volumes_from:
   - "stagingmysqldata"
  environment:
    MYSQL_ROOT_PASSWORD: password
  tty: true
  restart: always

production:
  image: jakubigla/apache-php
  ports:
   - "127.0.0.1:8080:8080"
   - "127.0.0.1:22222:22"
  links:
     - productionmysql
  volumes_from:
     - "productiondata"
  environment:
      APPLICATION_ENV: production
  tty: true
  restart: always

staging:
  image: jakubigla/apache-php
  ports:
   - "127.0.0.1:8081:8080"
  links:
       - stagingmysql
  volumes_from:
     - "stagingdata"
  environment:
      APPLICATION_ENV: staging
  tty: true
  restart: always
