jenkinsdata:
  image: jakubigla/jenkins-data-only
  volumes:
   - /docker-data/jenkins_home:/var/jenkins_home

productiondata:
  image: jakubigla/web-data-only
  volumes:
   - /docker-data/production/www:/www
   - /docker-data/production/vhosts:/etc/apache2/sites-available

stagingdata:
  image: jakubigla/web-data-only
  volumes:
   - /docker-data/staging/www:/www
   - /docker-data/production/vhosts:/etc/apache2/sites-available

productionmysqldata:
 image: jakubigla/mysql-data-only
 volumes:
  - /docker-data/production/mysql/data:/var/lib/mysql

stagingmysqldata:
 image: jakubigla/mysql-data-only
 volumes:
  - /docker-data/staging/mysql/data:/var/lib/mysql

jenkins:
  image: jenkins
  ports:
   - "8000:8080"
  volumes:
   - /var/jenkins_home
  tty: true
  restart: always

productionmysql:
  image: mysql
  volumes:
   - /var/lib/mysql
   - /etc/mysql/conf.d
  volumes_from:
   - "dataproduction"
  environment:
    MYSQL_ROOT_PASSWORD: password
  tty: true
  restart: always

stagingmysql:
  image: mysql
  volumes:
   - /var/lib/mysql
   - /etc/mysql/conf.d
  volumes_from:
   - "datastaging"
  environment:
    MYSQL_ROOT_PASSWORD: password
  tty: true
  restart: always

production:
  image: jakubigla/apache-php
  ports:
   - "127.0.0.1:8080:8080"
  volumes_from:
     - "dataproduction"
  environment:
      APPLICATION_ENV: production
  tty: true
  restart: always

staging:
  image: jakubigla/apache-php
  ports:
   - "127.0.0.1:8081:8080"
  volumes_from:
     - "datastaging"
  environment:
      APPLICATION_ENV: staging
  tty: true
  restart: always